from __future__ import annotations

import json
import shutil
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path

from sqlalchemy import delete, select

from touch_panel_studio.db.models.asset import Asset
from touch_panel_studio.db.models.component import Component
from touch_panel_studio.db.models.project import Project
from touch_panel_studio.db.models.screen import Screen
from touch_panel_studio.db.models.screen_action import ScreenAction
from touch_panel_studio.infrastructure.import_export.migrator import VersionMigrator
from touch_panel_studio.infrastructure.import_export.schemas import DataBundle, ProjectJson
from touch_panel_studio.infrastructure.import_export.validator import TemplateValidator
from touch_panel_studio.infrastructure.storage.project_storage import ProjectHandle, ProjectStorage, ProjectStorageError


class ImportError(RuntimeError):
    pass


@dataclass(frozen=True, slots=True)
class ProjectImportService:
    storage: ProjectStorage
    validator: TemplateValidator
    migrator: VersionMigrator

    def import_as_new_project(self, tpanel_file: Path, *, forced_code: str | None = None) -> ProjectHandle:
        if not tpanel_file.exists():
            raise ImportError("Файл .tpanel не найден.")

        with tempfile.TemporaryDirectory(prefix="tpanel_import_") as td:
            root = Path(td)
            self._extract_zip(tpanel_file, root)

            manifest = self.validator.validate_manifest(root / "manifest.json")
            schema = self.validator.validate_schema_version(root / "schema_version.json")
            self.migrator.migrate_to_current(root, schema)

            project_data = ProjectJson.model_validate_json((root / "project.json").read_text(encoding="utf-8"))
            bundle = self._read_bundle(root / "data")

            new_code = forced_code or project_data.code
            try:
                handle = self.storage.create_project(
                    name=project_data.name,
                    code=new_code,
                    description=project_data.description,
                )
            except ProjectStorageError:
                # If code collides, fall back to autogenerated code.
                handle = self.storage.create_project(
                    name=project_data.name,
                    code=None,
                    description=project_data.description,
                )

            # Backup fresh created project before filling (crash-safe import)
            backups_dir = self.storage.projects_root.parent / "runtime" / "backups" / "imports"
            backups_dir.mkdir(parents=True, exist_ok=True)
            try:
                shutil.make_archive(str(backups_dir / handle.meta.code), "zip", root_dir=str(handle.root_dir))
            except Exception:
                pass

            self._import_into_handle(handle, bundle)
            self._import_assets(handle, root / "assets")
            return handle

    def _extract_zip(self, file: Path, to_dir: Path) -> None:
        try:
            with zipfile.ZipFile(file, "r") as zf:
                zf.extractall(to_dir)
        except Exception as e:
            raise ImportError(f"Не удалось распаковать .tpanel: {e}") from e

    def _read_bundle(self, data_dir: Path) -> DataBundle:
        def read_list(name: str) -> list[dict]:
            p = data_dir / name
            if not p.exists():
                return []
            return json.loads(p.read_text(encoding="utf-8"))

        return DataBundle(
            screens=read_list("screens.json"),
            components=read_list("components.json"),
            screen_actions=read_list("screen_actions.json"),
            assets=read_list("assets.json"),
        )

    def _import_into_handle(self, handle: ProjectHandle, bundle: DataBundle) -> None:
        sf = handle.open_db()
        with sf.session() as s:
            project_id = s.scalar(select(Project.id).limit(1))
            if project_id is None:
                pr = Project(name=handle.meta.name, code=handle.meta.code, description=handle.meta.description, version=handle.meta.version)
                s.add(pr)
                s.flush()
                project_id = int(pr.id)
            else:
                project_id = int(project_id)

            # Clear existing data (new project should be empty, but keep safe)
            s.execute(delete(ScreenAction))
            s.execute(delete(Component))
            s.execute(delete(Screen))
            s.execute(delete(Asset))
            s.flush()

            screen_id_map: dict[int, int] = {}
            component_id_map: dict[int, int] = {}

            for src in bundle.screens:
                sc = Screen(
                    project_id=project_id,
                    name=src.name,
                    slug=src.slug,
                    screen_type=src.screen_type,
                    width=src.width,
                    height=src.height,
                    sort_order=src.sort_order,
                    is_home=src.is_home,
                    is_published=src.is_published,
                    background_type=src.background_type,
                    background_value=src.background_value,
                    background_fit=src.background_fit,
                    background_scale_percent=int(src.background_scale_percent),
                )
                s.add(sc)
                s.flush()
                screen_id_map[int(src.id)] = int(sc.id)

            for src in bundle.components:
                scid = screen_id_map.get(int(src.screen_id))
                if scid is None:
                    continue
                c = Component(
                    screen_id=scid,
                    type=src.type,
                    name=src.name,
                    x=src.x,
                    y=src.y,
                    width=src.width,
                    height=src.height,
                    z_index=src.z_index,
                    rotation=src.rotation,
                    is_visible=src.is_visible,
                    props_json=src.props_json,
                    style_json=src.style_json,
                    bindings_json=src.bindings_json,
                )
                s.add(c)
                s.flush()
                component_id_map[int(src.id)] = int(c.id)

            for src in bundle.screen_actions:
                src_screen = screen_id_map.get(int(src.source_screen_id))
                if src_screen is None:
                    continue
                src_comp = component_id_map.get(int(src.source_component_id)) if src.source_component_id is not None else None
                tgt_screen = screen_id_map.get(int(src.target_screen_id)) if src.target_screen_id is not None else None

                a = ScreenAction(
                    source_screen_id=src_screen,
                    source_component_id=src_comp,
                    trigger_type=src.trigger_type,
                    action_type=src.action_type,
                    target_screen_id=tgt_screen,
                    payload_json=src.payload_json,
                )
                s.add(a)

            for src in bundle.assets:
                a = Asset(
                    project_id=project_id,
                    asset_type=src.asset_type,
                    file_name=src.file_name,
                    original_name=src.original_name,
                    relative_path=src.relative_path,
                    mime_type=src.mime_type,
                    size_bytes=src.size_bytes,
                    checksum=src.checksum,
                )
                s.add(a)

            s.commit()

    def _import_assets(self, handle: ProjectHandle, extracted_assets_dir: Path) -> None:
        if not extracted_assets_dir.exists():
            return
        handle.assets_dir.mkdir(parents=True, exist_ok=True)
        for p in extracted_assets_dir.rglob("*"):
            if p.is_dir():
                continue
            rel = p.relative_to(extracted_assets_dir)
            dst = handle.assets_dir / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, dst)

